# Generated by Django 4.0.6 on 2022-08-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('customer_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.TextField(unique=True)),
                ('debit_card', models.TextField()),
                ('credit_card', models.TextField()),
                ('current_account', models.TextField()),
                ('checkbook_amount', models.IntegerField()),
                ('box_dollar', models.TextField(blank=True, null=True)),
                ('box_peso', models.TextField(blank=True, null=True)),
                ('withdraw_daily_max', models.IntegerField(blank=True, null=True)),
                ('transfer_comission', models.IntegerField(blank=True, null=True)),
                ('max_travel_reception', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_cliente',
                'managed': False,
            },
        ),
    ]
